services:
  db:
    image: postgres:15-alpine
    container_name: kavak-db
    restart: always
    environment:
      - POSTGRES_USER=kavak_user
      - POSTGRES_PASSWORD=kavak_pass
      - POSTGRES_DB=kavak_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: